-- ============================================================
-- Notitia - Script de base de datos (IBM Db2)
-- Ejecutar desde la ventana de comandos de Db2:
--   db2 -tvf script-base-de-datos.sql
-- Todos los datos de este script son ficticios.
-- ============================================================

CREATE DATABASE Dbexpo;
CONNECT TO Dbexpo;

-- Roles de usuario
CREATE TABLE Tipo_de_Clasificacion (
    IDClasificacion VARCHAR(200) NOT NULL PRIMARY KEY,
    Puesto VARCHAR(100)
);

INSERT INTO Tipo_de_Clasificacion VALUES
    ('1', 'Administrador'),
    ('2', 'Empleado'),
    ('3', 'Comun');

-- Usuarios
CREATE TABLE Usuarios (
    IDUsuario VARCHAR(200) NOT NULL PRIMARY KEY,
    Primer_Nombre VARCHAR(70),
    Segundo_Nombre VARCHAR(70),
    Primer_Apellido VARCHAR(70),
    Segundo_Apellido VARCHAR(70),
    DPI VARCHAR(70),
    Correo_Electronico VARCHAR(100),
    Número_de_telefono VARCHAR(50),
    Nombre_de_Usuario VARCHAR(100),
    Contrasena VARCHAR(100),
    Profesion_Oficio VARCHAR(100),
    Estado_Civil VARCHAR(100),
    Politicamente_Expuesto VARCHAR(100),
    IDClasificacion VARCHAR(200),
    Codigo_tarjeta VARCHAR(100),
    FOREIGN KEY (IDClasificacion) REFERENCES Tipo_de_Clasificacion(IDClasificacion)
);

INSERT INTO Usuarios VALUES
    ('1', 'Ana', 'María', 'López', 'Pérez', '1000000000101', 'admin@notitia.demo', '55550001', 'admin', '12345', 'Ingeniera', 'Soltera', 'No', '1', 'AA 11 22 33'),
    ('2', 'Carlos', 'Andrés', 'Méndez', 'Ruiz', '1000000000202', 'empleado@notitia.demo', '55550002', 'empleado', '12345', 'Contador', 'Casado', 'No', '2', 'BB 44 55 66'),
    ('3', 'Lucía', 'Fernanda', 'García', 'Morales', '1000000000303', 'cliente@notitia.demo', '55550003', 'cliente', '12345', 'Estudiante', 'Soltera', 'No', '3', 'CC 77 88 99');

-- Direcciones
CREATE TABLE Direccion (
    IDDireccion VARCHAR(200) NOT NULL PRIMARY KEY,
    IDUsuario VARCHAR(100),
    Direccion VARCHAR(100),
    Departamento VARCHAR(100),
    Zona VARCHAR(100),
    Municipio VARCHAR(100),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

INSERT INTO Direccion VALUES
    ('1', '1', '1a. Calle 1-01', 'Guatemala', 'Z.1', 'Guatemala'),
    ('2', '2', '2a. Avenida 2-02', 'Guatemala', 'Z.2', 'Mixco'),
    ('3', '3', '3a. Calle 3-03', 'Guatemala', 'Z.3', 'Villa Nueva');

-- Solicitudes de préstamo
CREATE TABLE Solicitudes_Prestamo (
    IDSolicitudPrestamo VARCHAR(200) NOT NULL PRIMARY KEY,
    IDUsuario VARCHAR(200),
    Nombre_Completo VARCHAR(200),
    Correo_Electronico VARCHAR(200),
    Numero_Telefonico VARCHAR(200),
    Fecha_de_Nacimiento DATE,
    DPI VARCHAR(70),
    NIT VARCHAR(70),
    Departamento VARCHAR(100),
    Zona_de_Residencia VARCHAR(100),
    Empresa_donde_labora VARCHAR(100),
    Antiguedad_Laboral VARCHAR(100),
    Ingresos_Mensuales DECIMAL(10,2),
    Monto_Deseado DECIMAL(10,2),
    Plazo_a_Pagar INT,
    Consolidar_Deudas VARCHAR(10),
    Recibe_salario_de_nuestro_banco VARCHAR(10),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

INSERT INTO Solicitudes_Prestamo VALUES
    ('1', '3', 'Lucía Fernanda García Morales', 'cliente@notitia.demo', '55550003', '2000-05-14', '1000000000303', '1234567-8', 'Guatemala', 'Z.3', 'Empresa Demo S.A.', '2022-02-10', 6000, 15000, 12, 'No', 'Si');

-- Cuentas bancarias
CREATE TABLE Cuentas_Bancarias (
    IDCuenta VARCHAR(200) NOT NULL PRIMARY KEY,
    IDUsuario VARCHAR(200),
    Nombre_de_Cuenta VARCHAR(100),
    Numero_de_Cuenta VARCHAR(100),
    Saldo DECIMAL(10,2),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

INSERT INTO Cuentas_Bancarias VALUES
    ('1', '1', 'Cuenta principal', '1000000000000001', 2500),
    ('2', '2', 'Cuenta principal', '1000000000000002', 2300),
    ('3', '3', 'Cuenta principal', '1000000000000003', 2800),
    ('4', '3', 'Ahorro', '1000000000000004', 1200);

-- Préstamos
CREATE TABLE Prestamos (
    IDPrestamo VARCHAR(200) NOT NULL PRIMARY KEY,
    IDUsuario VARCHAR(200),
    Monto DECIMAL(10,2),
    Plazo INT,
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

INSERT INTO Prestamos VALUES
    ('1', '3', 5000, 12);

-- Transferencias
CREATE TABLE Transferencias (
    IDTransferencia INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IDUsuario VARCHAR(200),
    Monto DECIMAL(10,2),
    Fecha DATE,
    IDCuenta VARCHAR(200),
    Tipo_de_ejecucion VARCHAR(150),
    Descripcion VARCHAR(250),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario),
    FOREIGN KEY (IDCuenta) REFERENCES Cuentas_Bancarias(IDCuenta)
);

-- Cuentas afiliadas de otros bancos
CREATE TABLE Afiliadas (
    IDAfiliada VARCHAR(200) NOT NULL PRIMARY KEY,
    Numero_de_cuenta VARCHAR(100),
    Banco VARCHAR(100),
    Saldo DECIMAL(10,2),
    IDUsuario VARCHAR(200),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

INSERT INTO Afiliadas VALUES
    ('1', '2000000000000001', 'Banco Virtud', 2300, '3');

-- Solicitudes de productos
CREATE TABLE Solicitud_Productos_Cuenta (
    IDSolCuenta VARCHAR(200) NOT NULL PRIMARY KEY,
    IDUsuario VARCHAR(200),
    Nombre_Completo VARCHAR(150),
    Numero_de_telefono VARCHAR(100),
    Correo_Electronico VARCHAR(150),
    Solicitud_de VARCHAR(150),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

INSERT INTO Solicitud_Productos_Cuenta VALUES
    ('1', '3', 'Lucía Fernanda García Morales', '55550003', 'cliente@notitia.demo', 'Ahorro');

-- Cuentas afiliadas de Notitia (terceros dentro del mismo banco)
CREATE TABLE Afiliadas_notitia (
    IDAfiliadas_not VARCHAR(200) NOT NULL PRIMARY KEY,
    Numero_de_cuenta VARCHAR(100),
    Nombre_cuenta VARCHAR(100),
    Saldo DECIMAL(10,2),
    IDUsuario VARCHAR(200),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario)
);

-- Estado de usuarios y cuentas (Activo / Deshabilitado)
ALTER TABLE Usuarios ADD Estado VARCHAR(20) DEFAULT 'Activo';
ALTER TABLE Cuentas_Bancarias ADD Estado VARCHAR(20) DEFAULT 'Activo';
